# Dataset for Tableau

In [1]:
# Import dependencies 
import pandas as pd

### Read the original CSV and Perform Basic Data Cleaning

In [2]:
crime_df = pd.read_csv('resources/CT_2013_2021.csv')
print(crime_df.shape) # columns & row 
crime_df.head()

(151492, 32)

,data_year,ori,pub_agency_name,pub_agency_unit,agency_type_name,state_abbr,state_name,division_name,county_name,region_name,...,weapon_code,weapon_name,prop_desc_code,data_year.1,prop_desc_code.1,prop_desc_name,stolen_value,recovered_value,recovered_flag,date_recovered
0,2021,TX0030000,Angelina,NaN,County,TX,Texas,West South Central,ANGELINA,South,...,NaN,NaN,20,2021,20,Money,375.0,0,False,NaN
1,2021,AL0010000,Jefferson,NaN,County,AL,Alabama,East South Central,JEFFERSON,South,...,NaN,NaN,77,2021,77,Other,1.0,0,False,NaN
2,2021,AL0010000,Jefferson,NaN,County,AL,Alabama,East South Central,JEFFERSON,South,...,NaN,NaN,65,2021,65,Identity Documents,0.0,0,False,NaN
3,2021,AL0010000,Jefferson,NaN,County,AL,Alabama,East South Central,JEFFERSON,South,...,NaN,NaN,13,2021,13,Firearms,320.0,0,False,NaN
4,2021,AL0010000,Jefferson,NaN,County,AL,Alabama,East South Central,JEFFERSON,South,...,NaN,NaN,77,2021,77,Other,1.0,0,False,NaN

In [3]:
crime_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151492 entries, 0 to 151491
Data columns (total 32 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   data_year              151492 non-null  int64
 1   ori                    151492 non-null  object
 2   pub_agency_name        151492 non-null  object
 3   pub_agency_unit        1422 non-null    object
 4   agency_type_name       151492 non-null  object
 5   state_abbr             151492 non-null  object
 6   state_name             151492 non-null  object
 7   division_name          151492 non-null  object
 8   county_name            151492 non-null  object
 9   region_name            151492 non-null  object
 10  population_group_code  151486 non-null  object
 11  population_group_desc  151486 non-null  object
 12  offense_code           151492 non-null  object
 13  offense_name           151492 non-null  object
 14  offender_race          83273 non-null   object
 15  offender_ethnicity     83273 non-null   object
 16  offender_age           78727 non-null   float64
 17  offender_sex           83273 non-null   object
 18  victim_type_code       151492 non-null  object
 19  victim_type_name       151492 non-null  object
 20  location_code          151492 non-null  int64
 21  location_name          151492 non-null  object
 22  weapon_code            12987 non-null   object
 23  weapon_name            12987 non-null   object
 24  prop_desc_code         151492 non-null  int64
 25  data_year.1            151492 non-null  int64
 26  prop_desc_code.1       151492 non-null  int64
 27  prop_desc_name         151492 non-null  object
 28  stolen_value           151221 non-null  float64
 29  recovered_value        151492 non-null  int64
 30  recovered_flag         151492 non-null  bool
 31  date_recovered         21471 non-null   object
dtypes: bool(1), float64(2), int64(6), object(23)
memory usage: 36.0+ MB

In [5]:
# Check the values 
crime_df.nunique()

data_year                   9
ori                      3912
pub_agency_name          2935
pub_agency_unit           147
agency_type_name            8
state_abbr                 50
state_name                 50
division_name              10
county_name              1227
region_name                 5
population_group_code      19
population_group_desc      19
offense_code               40
offense_name               40
offender_race               6
offender_ethnicity          4
offender_age               87
offender_sex                3
victim_type_code            9
victim_type_name            9
location_code              47
location_name              47
weapon_code                19
weapon_name                19
prop_desc_code             68
data_year.1                 9
prop_desc_code.1           68
prop_desc_name             68
stolen_value             5265
recovered_value          1144
recovered_flag              2
date_recovered           2431
dtype: int64

In [6]:
# Count NaN values under an entire DataFrame
crime_df.isna().sum()

data_year                     0
ori                           0
pub_agency_name               0
pub_agency_unit          150070
agency_type_name              0
state_abbr                    0
state_name                    0
division_name                 0
county_name                   0
region_name                   0
population_group_code         6
population_group_desc         6
offense_code                  0
offense_name                  0
offender_race             68219
offender_ethnicity        68219
offender_age              72765
offender_sex              68219
victim_type_code              0
victim_type_name              0
location_code                 0
location_name                 0
weapon_code              138505
weapon_name              138505
prop_desc_code                0
data_year.1                   0
prop_desc_code.1              0
prop_desc_name                0
stolen_value                271
recovered_value               0
recovered_flag                0
date_recovered           130021
dtype: int64

In [7]:
# Check the duplicate columns or not.
print(crime_df["data_year"].equals(crime_df["data_year.1"]))
print(crime_df["prop_desc_code"].equals(crime_df["prop_desc_code.1"]))

True
True

In [14]:
crimeD_df = crime_df.drop(columns=['ori','pub_agency_unit','data_year.1','prop_desc_code.1', 'date_recovered'])
print(crimeD_df.shape)
crimeD_df.head()    

# ORIGINATING AGENCY IDENTIFIER (ORI)

(151492, 27)

,data_year,pub_agency_name,agency_type_name,state_abbr,state_name,division_name,county_name,region_name,population_group_code,population_group_desc,...,victim_type_name,location_code,location_name,weapon_code,weapon_name,prop_desc_code,prop_desc_name,stolen_value,recovered_value,recovered_flag
0,2021,Angelina,County,TX,Texas,West South Central,ANGELINA,South,8B,"Non-MSA counties from 25,000 thru 99,999",...,Individual,25,Other/Unknown,NaN,NaN,20,Money,375.0,0,False
1,2021,Jefferson,County,AL,Alabama,East South Central,JEFFERSON,South,9A,"MSA counties 100,000 or over",...,Individual,20,Residence/Home,NaN,NaN,77,Other,1.0,0,False
2,2021,Jefferson,County,AL,Alabama,East South Central,JEFFERSON,South,9A,"MSA counties 100,000 or over",...,Individual,20,Residence/Home,NaN,NaN,65,Identity Documents,0.0,0,False
3,2021,Jefferson,County,AL,Alabama,East South Central,JEFFERSON,South,9A,"MSA counties 100,000 or over",...,Individual,20,Residence/Home,NaN,NaN,13,Firearms,320.0,0,False
4,2021,Jefferson,County,AL,Alabama,East South Central,JEFFERSON,South,9A,"MSA counties 100,000 or over",...,Individual,20,Residence/Home,NaN,NaN,77,Other,1.0,0,False

In [9]:
# check value count
crimeD_df.offender_race.value_counts()

White                                        34179
Black or African American                    24209
Unknown                                      23878
American Indian or Alaska Native               711
Asian                                          277
Native Hawaiian or Other Pacific Islander       19
Name: offender_race, dtype: int64

In [10]:
crimeD_df.offender_ethnicity.value_counts()

Not Hispanic or Latino    31554
Not Specified             23923
Unknown                   23702
Hispanic or Latino         4094
Name: offender_ethnicity, dtype: int64

In [11]:
crimeD_df.offender_age.value_counts()

0.0     19106
30.0     2443
25.0     2287
20.0     2134
18.0     2123
        ...
87.0        3
82.0        3
79.0        2
85.0        1
83.0        1
Name: offender_age, Length: 87, dtype: int64

In [12]:
crimeD_df.offender_sex.value_counts()

M    49186
U    20894
F    13193
Name: offender_sex, dtype: int64

In [13]:
crimeD_df.population_group_desc.value_counts()
# metropolitan statistical area (MSA)

Cities from 500,000 thru 999,999            20448
Cities from 25,000 thru 49,999              16711
Cities from 10,000 thru 24,999              16546
MSA counties 100,000 or over                16005
Cities from 50,000 thru 99,999              13123
Cities from 100,000 thru 249,999            12959
Cities from 2,500 thru 9,999                10181
Cities from 250,000 thru 499,999            10016
MSA counties from 25,000 thru 99,999         9178
Cities 1,000,000 or over                     7178
Non-MSA counties from 25,000 thru 99,999     5477
Non-MSA counties from 10,000 thru 24,999     4442
Cities under 2,500                           4330
Non-MSA counties under 10,000                1884
MSA counties from 10,000 thru 24,999         1749
MSA counties under 10,000                    1195
Non-MSA State Police                           58
Non-MSA counties 100,000 or over                4
MSA State Police                                2
Name: population_group_desc, dtype: int64

In [18]:
crimeD_df.weapon_name.value_counts()

Handgun                           4369
Personal Weapons                  3117
None                              1677
Other                              715
Knife/Cutting Instrument           710
Firearm                            679
Unknown                            460
Handgun (Automatic)                332
Blunt Object                       229
Rifle                              214
Motor Vehicle/Vessel               174
Other Firearm                       89
Firearm (Automatic)                 88
Shotgun                             79
Asphyxiation                        22
Drugs/Narcotics/Sleeping Pills      18
Rifle (Automatic)                   11
Shotgun (Automatic)                  2
Poison                               2
Name: weapon_name, dtype: int64

In [19]:
# Replace empty value with logical value
crimeD_df['offender_race'].fillna('Unknown', inplace = True)
crimeD_df['offender_ethnicity'].fillna('Unknown', inplace = True)
crimeD_df['offender_age'].fillna(0.0, inplace = True)
crimeD_df['offender_sex'].fillna('U', inplace = True)
crimeD_df['weapon_name'].fillna('Unknown', inplace = True)
crimeD_df['weapon_code'].fillna(95, inplace = True)
crimeD_df['stolen_value'].fillna(0, inplace = True)

In [20]:
## OW - Take a closer look at the entries with undefined population_group_description values.
crimeD_df.loc[crimeD_df.population_group_desc.isna() == True]

,data_year,pub_agency_name,agency_type_name,state_abbr,state_name,division_name,county_name,region_name,population_group_code,population_group_desc,...,victim_type_name,location_code,location_name,weapon_code,weapon_name,prop_desc_code,prop_desc_name,stolen_value,recovered_value,recovered_flag
2057,2021,Federal Bureau of Investigation,Federal,FS,Federal,Other,NOT SPECIFIED,Other,NaN,NaN,...,Government,5,Commercial/Office Building,95,Unknown,59,Firearm Accessories,700.0,0,False
24746,2021,United States Air Force Security Police,Federal,FS,Federal,Other,NOT SPECIFIED,Other,NaN,NaN,...,Individual,20,Residence/Home,95,Unknown,77,Other,350.0,0,False
68199,2020,United States Agency for International Develop...,Federal,FS,Federal,Other,NOT SPECIFIED,Other,NaN,NaN,...,Government,18,Parking/Drop Lot/Garage,95,Unknown,77,Other,3000000.0,0,False
73855,2020,United States Agency for International Develop...,Federal,FS,Federal,Other,NOT SPECIFIED,Other,NaN,NaN,...,Government,18,Parking/Drop Lot/Garage,95,Unknown,77,Other,3000000.0,3000000,True
73856,2020,United States Agency for International Develop...,Federal,FS,Federal,Other,NOT SPECIFIED,Other,NaN,NaN,...,Government,18,Parking/Drop Lot/Garage,95,Unknown,77,Other,3000000.0,3000000,True
73857,2020,United States Agency for International Develop...,Federal,FS,Federal,Other,NOT SPECIFIED,Other,NaN,NaN,...,Government,18,Parking/Drop Lot/Garage,95,Unknown,77,Other,3000000.0,3000000,True

In [23]:
## OW 
crimeD_df.population_group_desc = crimeD_df.population_group_desc.fillna("National")
crimeD_df.population_group_code = crimeD_df.population_group_code.fillna("0")

In [24]:
crimeD_df.isna().sum()

data_year                0
pub_agency_name          0
agency_type_name         0
state_abbr               0
state_name               0
division_name            0
county_name              0
region_name              0
population_group_code    0
population_group_desc    0
offense_code             0
offense_name             0
offender_race            0
offender_ethnicity       0
offender_age             0
offender_sex             0
victim_type_code         0
victim_type_name         0
location_code            0
location_name            0
weapon_code              0
weapon_name              0
prop_desc_code           0
prop_desc_name           0
stolen_value             0
recovered_value          0
recovered_flag           0
dtype: int64

In [25]:
# What are the offenses?
crimeD_df.offense_name.value_counts()

Theft From Motor Vehicle                       41562
All Other Larceny                              31440
Burglary/Breaking & Entering                   22584
Motor Vehicle Theft                            16175
Destruction/Damage/Vandalism of Property        8077
Theft From Building                             7263
Robbery                                         5964
False Pretenses/Swindle/Confidence Game         3522
Credit Card/Automated Teller Machine Fraud      2887
Drug/Narcotic Violations                        1774
Stolen Property Offenses                        1232
Identity Theft                                  1121
Impersonation                                   1085
Weapon Law Violations                            965
Simple Assault                                   888
Embezzlement                                     882
Drug Equipment Violations                        855
Aggravated Assault                               579
Counterfeiting/Forgery                           475
Kidnapping/Abduction                             426
Theft of Motor Vehicle Parts or Accessories      408
Shoplifting                                      315
Intimidation                                     236
Wire Fraud                                       181
Extortion/Blackmail                              114
Purse-snatching                                   96
Pocket-picking                                    86
Rape                                              66
Murder and Nonnegligent Manslaughter              47
Theft From Coin-Operated Machine or Device        45
Arson                                             43
Hacking/Computer Invasion                         38
Fondling                                          21
Pornography/Obscene Material                      16
Human Trafficking, Involuntary Servitude          16
Sodomy                                             3
Animal Cruelty                                     2
Bribery                                            1
Welfare Fraud                                      1
Sexual Assault With An Object                      1
Name: offense_name, dtype: int64

In [26]:
# OW - The priority for this project is anything related to stealing something.
excluded = ["Destruction/Damage/Vandalism of Property",
            "Drug/Narcotic Violations",
            "Impersonation",
            "Weapon Law Violations",
            "Drug Equipment Violations",
            "Simple Assault",
            "Aggravated Assault",
            "Kidnapping/Abduction",
            "Intimidation",
            "Extortion/Blackmail",
            "Rape",
            "Murder and Nonnegligent Manslaughter",
            "Arson",
            "Hacking/Computer Invasion",
            "Fondling",
            "Pornography/Obscene Material",
            "Human Trafficking, Involuntary Servitude",
            "Sodomy",
            "Animal Cruelty",
            "Bribery",
            "Sexual Assault With An Object"]

tableau_df = crimeD_df.loc[~crimeD_df.offense_name.isin(excluded)]

In [27]:
tableau_df.head(10)

,data_year,pub_agency_name,agency_type_name,state_abbr,state_name,division_name,county_name,region_name,population_group_code,population_group_desc,...,victim_type_name,location_code,location_name,weapon_code,weapon_name,prop_desc_code,prop_desc_name,stolen_value,recovered_value,recovered_flag
0,2021,Angelina,County,TX,Texas,West South Central,ANGELINA,South,8B,"Non-MSA counties from 25,000 thru 99,999",...,Individual,25,Other/Unknown,95,Unknown,20,Money,375.0,0,False
1,2021,Jefferson,County,AL,Alabama,East South Central,JEFFERSON,South,9A,"MSA counties 100,000 or over",...,Individual,20,Residence/Home,95,Unknown,77,Other,1.0,0,False
2,2021,Jefferson,County,AL,Alabama,East South Central,JEFFERSON,South,9A,"MSA counties 100,000 or over",...,Individual,20,Residence/Home,95,Unknown,65,Identity Documents,0.0,0,False
3,2021,Jefferson,County,AL,Alabama,East South Central,JEFFERSON,South,9A,"MSA counties 100,000 or over",...,Individual,20,Residence/Home,95,Unknown,13,Firearms,320.0,0,False
4,2021,Jefferson,County,AL,Alabama,East South Central,JEFFERSON,South,9A,"MSA counties 100,000 or over",...,Individual,20,Residence/Home,95,Unknown,77,Other,1.0,0,False
5,2021,Jefferson,County,AL,Alabama,East South Central,JEFFERSON,South,9A,"MSA counties 100,000 or over",...,Individual,20,Residence/Home,95,Unknown,65,Identity Documents,0.0,0,False
6,2021,Jefferson,County,AL,Alabama,East South Central,JEFFERSON,South,9A,"MSA counties 100,000 or over",...,Individual,20,Residence/Home,95,Unknown,13,Firearms,320.0,0,False
7,2021,Mobile,City,AL,Alabama,East South Central,MOBILE,South,2,"Cities from 100,000 thru 249,999",...,Individual,20,Residence/Home,95,Unknown,26,Radio/ TV/ VCR,900.0,0,False
8,2021,Mobile,City,AL,Alabama,East South Central,MOBILE,South,2,"Cities from 100,000 thru 249,999",...,Individual,20,Residence/Home,95,Unknown,17,Jewelry/ Precious Metals,400.0,0,False
9,2021,Mobile,City,AL,Alabama,East South Central,MOBILE,South,2,"Cities from 100,000 thru 249,999",...,Individual,25,Other/Unknown,95,Unknown,38,Vehicle Parts,9900.0,0,False

In [29]:
# Save taleau_df to a CSV file for tableau presentation purpose.
#tableau_df.to_csv('resources/tableau_use.csv', index=False)